#!/bin/sh
# Regenerates index.html from the site file.
#
# index.html is what GitHub Pages serves at the root of the domain; the .dc.html
# file is the one to edit. Run this after every change to the source, or the
# live site will keep serving the old version.
set -e
cd "$(dirname "$0")"
SRC="Great Lakes Exterior Cleaning Site.dc.html"
awk 'NR==1 { print; print "<!-- GENERATED by sync-index.sh from \"Great Lakes Exterior Cleaning Site.dc.html\" — do not edit this file directly. -->"; next } { print }' "$SRC" > index.html
echo "index.html regenerated from $SRC"
